### ISSUE TITLE
Error when using the plugin with the newest master (v1.12.0)

### ISSUE THREAD

**Issue by tom-rade** [NicolasSiver/nodebb-widget-ns-stats#7]
```
2018-12-15T13:26:01.999Z [5567/61] - error: Error: Cannot find module './src/emitter'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Module.require.main.require (/usr/src/app/require-main.js:8:10)
    at /usr/src/app/node_modules/nodebb-widget-ns-stats/widget/nodebb.js:8:31
    at Object.<anonymous> (/usr/src/app/node_modules/nodebb-widget-ns-stats/widget/nodebb.js:45:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /usr/src/app/node_modules/nodebb-widget-ns-stats/widget/job.js:7:18
    at Object.<anonymous> (/usr/src/app/node_modules/nodebb-widget-ns-stats/widget/job.js:65:3)

```

**Comment by NicolasSiver** [comment]
Check version 3.0. It should work in the NodeBB 1.11.x and I hope higher.

**Comment by tom-rade** [comment]
Thanks mate. Will try later.
